# Common part
service: pub-worker
runtime: go
env_variables:
  GOOGLE_CLOUD_PROJECT: tf-admin-aabm0pul
  PUBSUB_TOPIC: us.chicago-city.transportation.traffic-tracker-congestion-estimates
  PUBLISH_SERVICE: https://pub-worker-dot-tf-admin-aabm0pul.appspot.com/publish
  DATASOURCE_SODA_URI: https://data.cityofchicago.org/resource/8v9j-bter

# Standat environment:
#api_version: go1
#
#handlers:
#- url: /.*
#  script: _go_app
#
#automatic_scaling:
#  target_cpu_utilization: 0.75
#  max_instances: 4
#  min_instances: 1

# FLEX environment
env: flex
resources:
  cpu: .5
  memory_gb: 1.3
  disk_size_gb: 10
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.75
