# Common part
service: datasource-soda-worker
runtime: go

env_variables:
  GOOGLE_CLOUD_PROJECT: tf-admin-aabm0pul
  PUBSUB_TOPIC: us.chicago-city.transportation.traffic-tracker-congestion-estimates
  PUBLISH_SERVICE: https://datasource-soda-worker-dot-tf-admin-aabm0pul.appspot.com/publish
  DATASOURCE_SODA_URI: https://data.cityofchicago.org/resource/8v9j-bter
  DATADOG_API_KEY: '35976cc80ec87e62b9ba7784794edcb8719d88cc'

# Standat environment:
#api_version: go1
#handlers:
#- url: /.*
#  script: _go_app
#
#automatic_scaling:
#  target_cpu_utilization: 0.6
#  max_instances: 5
#  min_instances: 1

# FLEX environment
env: flex
resources:
  cpu: .5
  memory_gb: 1.3
  disk_size_gb: 10
network:
  instance_tag: dataservice-instance
  name: shared-network
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.5
