
# Common part
service: pubsub2cassandra-worker
runtime: go
env_variables:
  GOOGLE_CLOUD_PROJECT: tf-admin-aabm0pul
#  PUBSUB_TOPIC: us.chicago-city.transportation.traffic-tracker-congestion-estimates
#  DATASTORE_SERVICE: https://datastore-worker-dot-tf-admin-aabm0pul.appspot.com/entry
  DS_NAMESPACE: NorthAmerica
  DATASET_PARENT_KEY: ahNrfnRmLWFkbWluLWFhYm0wcHVscj0LEgdjYXRhbG9nGICAgICAgIAKDAsSCGNhdGVnb3J5GICAgICA8ogKDAsSB2RhdGFzZXQYgICAgIDXjAoMogEMTm9ydGhBbWVyaWNh

# Standat environment:
api_version: go1
handlers:
- url: /.*
  script: _go_app

automatic_scaling:
  target_cpu_utilization: 0.6
  max_instances: 25
  min_instances: 1

# FLEX environment
#env: flex
#resources:
#  cpu: .5
#  memory_gb: 1.3
#  disk_size_gb: 10
#automatic_scaling:
#  min_num_instances: 1
#  max_num_instances: 2
#  cool_down_period_sec: 60
#  cpu_utilization:
#    target_utilization: 0.75
